fixup! hooks: Check for uncommitted changes

diff --git a/.hooks/pre-push b/.hooks/pre-push
--- a/.hooks/pre-push
+++ b/.hooks/pre-push
@@ -1,9 +1,11 @@
 #!/usr/bin/env bash
 
-if ! git diff-index --quiet HEAD --; then
-    echo "You have uncommitted changes. Please commit or stash them before pushing."
-    exit 1
-fi
+function check_uncommitted_changes() {
+    if ! git diff-index --quiet HEAD --; then
+        echo "You have uncommitted changes. Please commit or stash them before pushing."
+        exit 1
+    fi
+}
 
 function lint()
 {
@@ -14,6 +16,12 @@ function lint()
     fi
 }
 
+# Fail early if uncommitted changes
+check_uncommitted_changes
+
 lint botbrain
 lint simple_sim
 lint trainer
+
+# Clippy can change lock files
+check_uncommitted_changes 
